export interface User {
  id: number
  name: string
  username: string
  email: string
  created_at: Date
  updated_at: Date
  lastname: string
  role_id: number
  avatar_file_name: string
  avatar_content_type: string
  avatar_file_size: number
  avatar_updated_at: Date
  provider: string
  uid: string
  authentication_token: string
  cover_file_name: null
  cover_content_type: null
  cover_file_size: null
  cover_updated_at: null
  aboutme: string
  points: null
  token_channel: string
  photo_url: string
  wizard: boolean
  change_password: boolean
  facebook_url: string
  twitter_url: string
  linkedin_url: string
  studies: string
  job: string
  ranking: number
  country_id: number
  process: string
  customer_status: string
  invite_ready: null
  opportunities: number
  skills: string[]
  role: string
  rut: string
  contact: string
  address: string
  city: string
  minutes_studied: number
  birthdate: Date
  current_degree: string
  user_type: string
  terms_and_conditions: boolean
  postal_code: null
  company_id: null
  courses_free: CoursesFree
  discount_coupon_id: null
  allow_search: boolean
  segment: string
  permission_degrees: any[]
  vouchers: number
  number_followers: number
  number_followeds: number
  education_id: null
  education_type: string
  actual_position: null
  public_profile: null
  verified: null
  responsable_id: null
  headline: string
  number_post: number
  avatar_url: string
  avatar_url_small: string
  full_name: string
}

export interface CoursesFree {
}
